;
; File generated by cc65 v 2.15
;
	.fopt		compiler,"cc65 v 2.15"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_factorial

; ---------------------------------------------------------------
; void __near__ factorial (int, __near__ unsigned int *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_factorial: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	ldx     #$00
	lda     #$01
	ldy     #$00
	jsr     staxysp
L0002:	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     tosuleax
	jne     L0005
	jmp     L0003
L0005:	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     tosumulax
	ldy     #$00
	jsr     staxspidx
	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0002
L0003:	jsr     incsp6
	rts

.endproc

