;
; File generated by cc65 v 2.15
;
	.fopt		compiler,"cc65 v 2.15"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_recursive_fibonacci

; ---------------------------------------------------------------
; int __near__ recursive_fibonacci (int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_recursive_fibonacci: near

.segment	"CODE"

	jsr     pushax
	ldy     #$01
	jsr     ldaxysp
	cpx     #$00
	bne     L0004
	cmp     #$00
L0004:	jsr     booleq
	jeq     L0002
	ldx     #$00
	lda     #$00
	jmp     L0001
L0002:	ldy     #$01
	jsr     ldaxysp
	cpx     #$00
	bne     L0008
	cmp     #$01
L0008:	jsr     booleq
	jeq     L0006
	ldx     #$00
	lda     #$01
	jmp     L0001
L0006:	ldy     #$01
	jsr     ldaxysp
	jsr     decax1
	jsr     _recursive_fibonacci
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     decax2
	jsr     _recursive_fibonacci
	jsr     tosaddax
	jmp     L0001
L0001:	jsr     incsp2
	rts

.endproc

