;
; File generated by cc65 v 2.15
;
	.fopt		compiler,"cc65 v 2.15"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_malloc
	.export		_vectorAdd

; ---------------------------------------------------------------
; __near__ int * __near__ vectorAdd (__near__ int *, __near__ int *, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_vectorAdd: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp4
	ldy     #$05
	jsr     ldaxysp
	jsr     shlax1
	jsr     _malloc
	ldy     #$00
	jsr     staxysp
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxysp
L0005:	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     tosultax
	jne     L0008
	jmp     L0006
L0008:	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     aslax1
	jsr     tosaddax
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     aslax1
	jsr     tosaddax
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     aslax1
	jsr     tosaddax
	ldy     #$01
	jsr     ldaxidx
	jsr     tosaddax
	ldy     #$00
	jsr     staxspidx
	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0005
L0006:	ldy     #$01
	jsr     ldaxysp
	jmp     L0001
L0001:	ldy     #$0A
	jsr     addysp
	rts

.endproc

